"""Sensor entities for the Weather Station integration for old endpoint."""

from typing import cast

from homeassistant.components.sensor import SensorDeviceClass, SensorStateClass
from homeassistant.const import (
    CONCENTRATION_MICROGRAMS_PER_CUBIC_METER,
    CONCENTRATION_PARTS_PER_BILLION,
    CONCENTRATION_PARTS_PER_MILLION,
    DEGREE,
    PERCENTAGE,
    UV_INDEX,
    UnitOfIrradiance,
    UnitOfLength,
    UnitOfPrecipitationDepth,
    UnitOfPressure,
    UnitOfSpeed,
    UnitOfTemperature,
    UnitOfVolumetricFlux,
)

from .const import (
    BARO_PRESSURE,
    BATTERY,
    CHILL_INDEX,
    CO,
    CO2,
    DEW_POINT,
    FEELS_LIKE,
    HCHO,
    HEAT_INDEX,
    HUMIDITY,
    INDOOR_HUMIDITY,
    INDOOR_TEMP,
    LIGHTNING_DISTANCE,
    LIGHTNING_STRIKE_COUNT_DURING_1_DAY,
    LIGHTNING_STRIKE_COUNT_DURING_1_HOUR,
    LIGHTNING_STRIKE_COUNT_DURING_5_MINUTES,
    LIGHTNING_STRIKE_COUNT_DURING_30_MINUTES,
    LIGHTNING_STRIKE_COUNT_LAST_HOUR,
    LIGHTNING_STRIKE_TIME,
    OUTSIDE_HUMIDITY,
    OUTSIDE_TEMP,
    PM10,
    PM10_AQI,
    PM25,
    PM25_AQI,
    RAIN_RATE,
    RAINFALL_DAILY,
    RAINFALL_HOURLY,
    RAINFALL_MONTHLY,
    RAINFALL_WEEKLY,
    RAINFALL_YEARLY,
    SOLAR_RADIATION,
    T8_BATTERY,
    T9_BATTERY,
    T10_BATTERY,
    T11_BATTERY,
    T234_HUMIDITY_KEYS,
    T234_TEMP_KEYS,
    TEMPERATURE,
    UV,
    VOC,
    WBGT_TEMP,
    WIND_AZIMUTH,
    WIND_DIR,
    WIND_GUST,
    WIND_SPEED,
    UnitOfDir,
    VOCLevel,
)
from .helpers import (
    battery_5step_to_pct,
    minutes_since_to_timestamp,
    voc_level_to_text,
    wind_dir_to_text,
)
from .sensors_common import WeatherSensorEntityDescription


def _temp_desc(key: str, unit: UnitOfTemperature) -> WeatherSensorEntityDescription:
    return WeatherSensorEntityDescription(
        key=key,
        native_unit_of_measurement=unit,
        state_class=SensorStateClass.MEASUREMENT,
        device_class=SensorDeviceClass.TEMPERATURE,
        icon="mdi:thermometer",
        translation_key=TEMPERATURE,
        value_fn=lambda data: cast("float", data),
    )


def _humidity_desc(
    key: str, icon: str = "mdi:water-percent"
) -> WeatherSensorEntityDescription:
    return WeatherSensorEntityDescription(
        key=key,
        native_unit_of_measurement=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        device_class=SensorDeviceClass.HUMIDITY,
        icon=icon,
        translation_key=HUMIDITY,
        value_fn=lambda data: cast("int", data),
    )


_CHANNELS_WSLINK = tuple(zip(T234_TEMP_KEYS, T234_HUMIDITY_KEYS, strict=False))


def _channel_descriptions_wslink() -> tuple[WeatherSensorEntityDescription, ...]:
    out: list[WeatherSensorEntityDescription] = []
    for temp_key, hum_key in _CHANNELS_WSLINK:
        out.append(_temp_desc(temp_key, UnitOfTemperature.CELSIUS))
        out.append(_humidity_desc(hum_key))
    return tuple(out)


SENSOR_TYPES_WSLINK: tuple[WeatherSensorEntityDescription, ...] = (
    _temp_desc(INDOOR_TEMP, UnitOfTemperature.CELSIUS),
    _humidity_desc(INDOOR_HUMIDITY),
    _temp_desc(OUTSIDE_TEMP, UnitOfTemperature.CELSIUS),
    _humidity_desc(OUTSIDE_HUMIDITY, icon="mdi:cloud-percent"),
    WeatherSensorEntityDescription(
        key=DEW_POINT,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:thermometer-lines",
        device_class=SensorDeviceClass.TEMPERATURE,
        translation_key=DEW_POINT,
        value_fn=lambda data: cast("float", data),
    ),
    WeatherSensorEntityDescription(
        key=BARO_PRESSURE,
        native_unit_of_measurement=UnitOfPressure.HPA,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:gauge",
        device_class=SensorDeviceClass.ATMOSPHERIC_PRESSURE,
        suggested_unit_of_measurement=UnitOfPressure.HPA,
        translation_key=BARO_PRESSURE,
        value_fn=lambda data: cast("float", data),
    ),
    WeatherSensorEntityDescription(
        key=WIND_SPEED,
        native_unit_of_measurement=UnitOfSpeed.METERS_PER_SECOND,
        state_class=SensorStateClass.MEASUREMENT,
        device_class=SensorDeviceClass.WIND_SPEED,
        suggested_unit_of_measurement=UnitOfSpeed.KILOMETERS_PER_HOUR,
        icon="mdi:weather-windy",
        translation_key=WIND_SPEED,
        value_fn=lambda data: cast("int", data),
    ),
    WeatherSensorEntityDescription(
        key=WIND_GUST,
        native_unit_of_measurement=UnitOfSpeed.METERS_PER_SECOND,
        state_class=SensorStateClass.MEASUREMENT,
        device_class=SensorDeviceClass.WIND_SPEED,
        suggested_unit_of_measurement=UnitOfSpeed.KILOMETERS_PER_HOUR,
        icon="mdi:windsock",
        translation_key=WIND_GUST,
        value_fn=lambda data: cast("float", data),
    ),
    WeatherSensorEntityDescription(
        key=WIND_DIR,
        native_unit_of_measurement=DEGREE,
        state_class=SensorStateClass.MEASUREMENT_ANGLE,
        device_class=SensorDeviceClass.WIND_DIRECTION,
        suggested_display_precision=None,
        icon="mdi:sign-direction",
        translation_key=WIND_DIR,
        value_fn=lambda data: cast("int", data),
    ),
    WeatherSensorEntityDescription(
        key=WIND_AZIMUTH,
        icon="mdi:sign-direction",
        value_fn=lambda data: cast("str", wind_dir_to_text(data)),
        device_class=SensorDeviceClass.ENUM,
        options=list(UnitOfDir),
        translation_key=WIND_AZIMUTH,
    ),
    WeatherSensorEntityDescription(
        key=RAIN_RATE,
        native_unit_of_measurement=UnitOfVolumetricFlux.MILLIMETERS_PER_HOUR,
        device_class=SensorDeviceClass.PRECIPITATION_INTENSITY,
        state_class=SensorStateClass.MEASUREMENT,
        suggested_unit_of_measurement=UnitOfVolumetricFlux.MILLIMETERS_PER_HOUR,
        suggested_display_precision=2,
        icon="mdi:weather-pouring",
        translation_key=RAIN_RATE,
        value_fn=lambda data: cast("float", data),
    ),
    WeatherSensorEntityDescription(
        key=RAINFALL_DAILY,
        native_unit_of_measurement=UnitOfPrecipitationDepth.MILLIMETERS,
        device_class=SensorDeviceClass.PRECIPITATION,
        state_class=SensorStateClass.MEASUREMENT,
        suggested_unit_of_measurement=UnitOfPrecipitationDepth.MILLIMETERS,
        suggested_display_precision=2,
        icon="mdi:weather-pouring",
        translation_key=RAINFALL_DAILY,
        value_fn=lambda data: cast("float", data),
    ),
    WeatherSensorEntityDescription(
        key=RAINFALL_HOURLY,
        native_unit_of_measurement=UnitOfPrecipitationDepth.MILLIMETERS,
        device_class=SensorDeviceClass.PRECIPITATION,
        state_class=SensorStateClass.MEASUREMENT,
        suggested_unit_of_measurement=UnitOfPrecipitationDepth.MILLIMETERS,
        suggested_display_precision=2,
        icon="mdi:weather-pouring",
        translation_key=RAINFALL_HOURLY,
        value_fn=lambda data: cast("float", data),
    ),
    WeatherSensorEntityDescription(
        key=RAINFALL_WEEKLY,
        native_unit_of_measurement=UnitOfPrecipitationDepth.MILLIMETERS,
        device_class=SensorDeviceClass.PRECIPITATION,
        state_class=SensorStateClass.MEASUREMENT,
        suggested_unit_of_measurement=UnitOfPrecipitationDepth.MILLIMETERS,
        suggested_display_precision=2,
        icon="mdi:weather-pouring",
        translation_key=RAINFALL_WEEKLY,
        value_fn=lambda data: cast("float", data),
    ),
    WeatherSensorEntityDescription(
        key=RAINFALL_MONTHLY,
        native_unit_of_measurement=UnitOfPrecipitationDepth.MILLIMETERS,
        device_class=SensorDeviceClass.PRECIPITATION,
        state_class=SensorStateClass.MEASUREMENT,
        suggested_unit_of_measurement=UnitOfPrecipitationDepth.MILLIMETERS,
        suggested_display_precision=2,
        icon="mdi:weather-pouring",
        translation_key=RAINFALL_MONTHLY,
        value_fn=lambda data: cast("float", data),
    ),
    WeatherSensorEntityDescription(
        key=RAINFALL_YEARLY,
        native_unit_of_measurement=UnitOfPrecipitationDepth.MILLIMETERS,
        device_class=SensorDeviceClass.PRECIPITATION,
        state_class=SensorStateClass.MEASUREMENT,
        suggested_unit_of_measurement=UnitOfPrecipitationDepth.MILLIMETERS,
        suggested_display_precision=2,
        icon="mdi:weather-pouring",
        translation_key=RAINFALL_YEARLY,
        value_fn=lambda data: cast("float", data),
    ),
    WeatherSensorEntityDescription(
        key=SOLAR_RADIATION,
        native_unit_of_measurement=UnitOfIrradiance.WATTS_PER_SQUARE_METER,
        state_class=SensorStateClass.MEASUREMENT,
        device_class=SensorDeviceClass.IRRADIANCE,
        icon="mdi:weather-sunny",
        translation_key=SOLAR_RADIATION,
        value_fn=lambda data: cast("float", data),
    ),
    WeatherSensorEntityDescription(
        key=UV,
        name=UV,
        state_class=SensorStateClass.MEASUREMENT,
        native_unit_of_measurement=UV_INDEX,
        icon="mdi:sunglasses",
        translation_key=UV,
        value_fn=lambda data: cast("float", data),
    ),
    *_channel_descriptions_wslink(),
    WeatherSensorEntityDescription(
        key=HEAT_INDEX,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        state_class=SensorStateClass.MEASUREMENT,
        device_class=SensorDeviceClass.TEMPERATURE,
        suggested_unit_of_measurement=UnitOfTemperature.CELSIUS,
        suggested_display_precision=2,
        icon="mdi:thermometer",
        translation_key=HEAT_INDEX,
        value_fn=lambda data: cast("int", data),
    ),
    WeatherSensorEntityDescription(
        key=FEELS_LIKE,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        state_class=SensorStateClass.MEASUREMENT,
        device_class=SensorDeviceClass.TEMPERATURE,
        suggested_unit_of_measurement=UnitOfTemperature.CELSIUS,
        suggested_display_precision=1,
        icon="mdi:thermometer",
        translation_key=FEELS_LIKE,
        value_fn=lambda data: cast("float", data),
    ),
    WeatherSensorEntityDescription(
        key=CHILL_INDEX,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        state_class=SensorStateClass.MEASUREMENT,
        device_class=SensorDeviceClass.TEMPERATURE,
        suggested_unit_of_measurement=UnitOfTemperature.CELSIUS,
        suggested_display_precision=1,
        icon="mdi:thermometer",
        translation_key=CHILL_INDEX,
        value_fn=lambda data: cast("int", data),
    ),
    WeatherSensorEntityDescription(
        key=WBGT_TEMP,
        translation_key=WBGT_TEMP,
        icon="mdi:thermometer",
        state_class=SensorStateClass.MEASUREMENT,
        device_class=SensorDeviceClass.TEMPERATURE,
        native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        suggested_display_precision=1,
        value_fn=lambda data: cast("int", data),
    ),
    WeatherSensorEntityDescription(
        key=LIGHTNING_STRIKE_TIME,
        translation_key=LIGHTNING_STRIKE_TIME,
        icon="mdi:timer-star",
        device_class=SensorDeviceClass.TIMESTAMP,
        value_fn=minutes_since_to_timestamp,
    ),
    WeatherSensorEntityDescription(
        key=LIGHTNING_DISTANCE,
        translation_key=LIGHTNING_DISTANCE,
        icon="mdi:signal-distance-variant",
        state_class=SensorStateClass.MEASUREMENT,
        device_class=SensorDeviceClass.DISTANCE,
        native_unit_of_measurement=UnitOfLength.KILOMETERS,
        suggested_display_precision=0,
        value_fn=lambda data: cast("int", data),
    ),
    WeatherSensorEntityDescription(
        key=LIGHTNING_STRIKE_COUNT_LAST_HOUR,
        translation_key=LIGHTNING_STRIKE_COUNT_LAST_HOUR,
        icon="mdi:counter",
        value_fn=lambda data: cast("int", data),
    ),
    WeatherSensorEntityDescription(
        key=LIGHTNING_STRIKE_COUNT_DURING_5_MINUTES,
        translation_key=LIGHTNING_STRIKE_COUNT_DURING_5_MINUTES,
        icon="mdi:counter",
        value_fn=lambda data: cast("int", data),
    ),
    WeatherSensorEntityDescription(
        key=LIGHTNING_STRIKE_COUNT_DURING_30_MINUTES,
        translation_key=LIGHTNING_STRIKE_COUNT_DURING_30_MINUTES,
        icon="mdi:counter",
        value_fn=lambda data: cast("int", data),
    ),
    WeatherSensorEntityDescription(
        key=LIGHTNING_STRIKE_COUNT_DURING_1_HOUR,
        translation_key=LIGHTNING_STRIKE_COUNT_DURING_1_HOUR,
        icon="mdi:counter",
        value_fn=lambda data: cast("int", data),
    ),
    WeatherSensorEntityDescription(
        key=LIGHTNING_STRIKE_COUNT_DURING_1_DAY,
        translation_key=LIGHTNING_STRIKE_COUNT_DURING_1_DAY,
        icon="mdi:counter",
        value_fn=lambda data: cast("int", data),
    ),
    WeatherSensorEntityDescription(
        key=PM25,
        translation_key=PM25,
        device_class=SensorDeviceClass.PM25,
        native_unit_of_measurement=CONCENTRATION_MICROGRAMS_PER_CUBIC_METER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:molecule",
        value_fn=lambda data: cast("int", data),
    ),
    WeatherSensorEntityDescription(
        key=PM10,
        translation_key=PM10,
        device_class=SensorDeviceClass.PM10,
        native_unit_of_measurement=CONCENTRATION_MICROGRAMS_PER_CUBIC_METER,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:molecule",
        value_fn=lambda data: cast("int", data),
    ),
    WeatherSensorEntityDescription(
        key=PM25_AQI,
        translation_key=PM25_AQI,
        device_class=SensorDeviceClass.AQI,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:blur",
        value_fn=lambda data: cast("int", data),
    ),
    WeatherSensorEntityDescription(
        key=PM10_AQI,
        translation_key=PM10_AQI,
        device_class=SensorDeviceClass.AQI,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:blur",
        value_fn=lambda data: cast("int", data),
    ),
    WeatherSensorEntityDescription(
        key=T8_BATTERY,
        translation_key=BATTERY,
        device_class=SensorDeviceClass.BATTERY,
        native_unit_of_measurement=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=0,
        value_fn=battery_5step_to_pct,
    ),
    WeatherSensorEntityDescription(
        key=HCHO,
        translation_key=HCHO,
        device_class=SensorDeviceClass.VOLATILE_ORGANIC_COMPOUNDS_PARTS,
        native_unit_of_measurement=CONCENTRATION_PARTS_PER_BILLION,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:molecule",
        value_fn=lambda data: cast("int", data),
    ),
    WeatherSensorEntityDescription(
        key=VOC,
        translation_key=VOC,
        device_class=SensorDeviceClass.ENUM,
        options=list(VOCLevel),
        icon="mdi:air-filter",
        value_fn=lambda data: cast("str", voc_level_to_text(data)),
    ),
    WeatherSensorEntityDescription(
        key=T9_BATTERY,
        translation_key=BATTERY,
        device_class=SensorDeviceClass.BATTERY,
        native_unit_of_measurement=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=0,
        value_fn=battery_5step_to_pct,
    ),
    WeatherSensorEntityDescription(
        key=CO2,
        translation_key=CO2,
        device_class=SensorDeviceClass.CO2,
        native_unit_of_measurement=CONCENTRATION_PARTS_PER_MILLION,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:molecule-co2",
        value_fn=lambda data: cast("int", data),
    ),
    WeatherSensorEntityDescription(
        key=T10_BATTERY,
        translation_key=BATTERY,
        device_class=SensorDeviceClass.BATTERY,
        native_unit_of_measurement=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=0,
        value_fn=battery_5step_to_pct,
    ),
    WeatherSensorEntityDescription(
        key=CO,
        translation_key=CO,
        device_class=SensorDeviceClass.CO,
        native_unit_of_measurement=CONCENTRATION_PARTS_PER_MILLION,
        state_class=SensorStateClass.MEASUREMENT,
        icon="mdi:molecule-co",
        value_fn=lambda data: cast("int", data),
    ),
    WeatherSensorEntityDescription(
        key=T11_BATTERY,
        translation_key=BATTERY,
        device_class=SensorDeviceClass.BATTERY,
        native_unit_of_measurement=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=0,
        value_fn=battery_5step_to_pct,
    ),
)
